### PR TITLE
CENG-1795 Faraday >= 2.0 removed the authorization helper method

### PR DESCRIPTION
**Pull request by johnwu96822**
- [x] @abdulchaudhrycoupa
- [ ] @jakirsshaikh

## Generated Reviewers

<details>
  <summary><em>:warning: Do not modify anything in this section! :warning:</em></summary>
  <em>The content in this section is managed automatically, and any manual changes to it will be ignored and overwritten the next time the code review status is refreshed! View <a href="https://cody.coupa.engineering/repos/coupa/sand-ruby/pull/39">this PR</a> on Cody to see the current code review status.</em>
</details>

### CODE REVIEW

**Review by abdulchaudhrycoupa — APPROVED** [review]

**Review by johnny-lai — APPROVED** [review]

**Comment by johnwu96822** [comment]
cody rebuild

**Comment by johnwu96822** [comment]
cody rebuild

**Review by jakirsshaikh — APPROVED** [review]
LGTM

**Comment by johnwu96822** [comment]
[lockit v5.0.2] merged via Lockit CLI on 2023-04-13 14:07:44.494513 +0800 CST m=+6.660388926

**Pull request merged**
